export const FETCH_TODOS_START = "FETCH_TODOS_START";
export const FETCH_TODOS_SUCCEEDED = "FETCH_TODOS_SUCCEEDED";
export const FETCH_TODOS_FAILED = "FETCH_TODOS_FAILED";

export const ADD_TODO_START = "ADD_TODO_START";
export const ADD_TODO_SUCCEEDED = "ADD_TODO_SUCCEEDED";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";

export const EDIT_TODO_START = "EDIT_TODO_START";
export const EDIT_TODO_SUCCEEDED = "EDIT_TODO_SUCCEEDED";
export const EDIT_TODO_FAILED = "EDIT_TODO_FAILED";

export const REMOVE_TODO_START = "REMOVE_TODO_START";
export const REMOVE_TODO_SUCCEEDED = "REMOVE_TODO_SUCCEEDED";
export const REMOVE_TODO_FAILED = "REMOVE_TODO_FAILED";

export const COMPLETE_TODO_START = "COMPLETE_TODO_START";
export const COMPLETE_TODO_SUCCEEDED = "COMPLETE_TODO_SUCCEEDED";
export const COMPLETE_TODO_FAILED = "COMPLETE_TODO_FAILED";

export default {
	FETCH_TODOS_START,
	FETCH_TODOS_SUCCEEDED,
	FETCH_TODOS_FAILED,
	ADD_TODO_START,
	ADD_TODO_SUCCEEDED,
	ADD_TODO_FAILED,
	EDIT_TODO_START,
	EDIT_TODO_SUCCEEDED,
	EDIT_TODO_FAILED,
	REMOVE_TODO_START,
	REMOVE_TODO_SUCCEEDED,
	REMOVE_TODO_FAILED,
	COMPLETE_TODO_START,
	COMPLETE_TODO_SUCCEEDED,
	COMPLETE_TODO_FAILED,
};