export const FETCH_TODOS_START = "FETCH_TODOS_START";
export const FETCH_TODOS_SUCCEEDED = "FETCH_TODOS_SUCCEEDED";
export const FETCH_TODOS_FAILED = "FETCH_TODOS_FAILED";

export const SET_TODOS = "SET_TODOS";

export const ADD_TODO_START = "ADD_TODO_START";
export const ADD_TODO_SUCCEEDED = "ADD_TODO_SUCCEEDED";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";
export const ADD_TODO = "ADD_TODO";

export const REMOVE_TODO = "REMOVE_TODO";
export const EDIT_TODOS = "EDIT_TODOS";


export default {
	FETCH_TODOS_START,
	FETCH_TODOS_SUCCEEDED,
	FETCH_TODOS_FAILED,
	SET_TODOS,
	ADD_TODO_START,
	ADD_TODO_SUCCEEDED,
	ADD_TODO_FAILED,
	ADD_TODO,
	REMOVE_TODO,
	EDIT_TODOS,
};